<div class="HomePage">
	<div class="HomePage-content">
		<div class="row">
			<div class="col-sm-12">
				<h1>Ma boutique en ligne</h1>
				<h2>Votre mission si vous l'acceptez ...</h2>
				<div>
					<p>
						<strong>Développer</strong> une micro-boutique en ligne ! Pour ce faire :
					</p>
					<h3>Créer la base de donnée</h3>
					<ul>
						<li>des produits</li>
						<li>des catégories <small>(un produits peut appartenir à plusieurs catégories et une catégorie peut contenir plusieurs produits)</small></li>
						<li>des commandes <small>(une commande contient 1 ou plusieurs produit)</small></li>
					</ul>
					<h3>Créer une page d'accueil qui présente la boutique et y afficher les 4 derniers produit d'une catégorie (peu importe la catégorie : Top Ventes par exemple)</h3>
					<ul>
						<li>Modifier le HomeController déjà présent</li>
						<li>Créer le bon Manager pour récuperer les données</li>
						<li>Modifier la bonne vue et afficher les données <small>(design travaillé svp)</small></li>
					</ul>
					<h3>Créer une page catégorie qui affiche les produits d'une catégorie par ordre alphabétique</h3>
					<ul>
						<li>Créer la route qui permettrait d'afficher un rayon grâce à l'URL /categorie/{idcat}/{nomcate}</li>
						<li>Créer le bon controleur</li>
						<li>Créer la méthode permettant d'afficher une catégorie <small>(en lien avec la route)</small></li>
					</ul>
					<h3>Créer une page permettant d'afficher un produit (fiche produit)</h3>
					<ul>
						<li>Faire en sorte que la route /produits/{nomcate}/{idproduit}/{nomproduit} affiche une page produit avec les infos du produit concerné</li>
						<li>Possibilté d'ajouter le produit au panier avec quantité</li>
					</ul>
					<h3>Créer un tunnel de commande</h3>
					<ul>
						<li>Panier</li>
						<li>Récap. de commande et mode de livraison</li>
						<li>Paiement (fictif)</li>
					</ul>
				</div>
				<h2>BONUS</h2>
				<strong>Pour une boutique fonctionnelle</strong>
				<h3>Gérer l'espace client</h3>
				<ul>
					<li>Accès "Mon compte"</li>
					<li>Validation du panier si et seulement si un client s'est connecté ou vient de créer son compte</li>
				</ul>
				<h3>Gérer le backoffice</h3>
				<ul>
					<li>Affichage des commandes</li>
					<li>Gestion des catégories</li>
					<li>Gestion des produits</li>
					<li>Gestion des comptes client</li>
				</ul>
			</div>
		</div>
	</div>
</div>

