<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?= !empty($title) ? $title : "Backoffice MyMVC" ?></title>

    <!-- Custom fonts for this template-->
    <link href="/administration/Content/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="/administration/Content/css/sb-admin-2.min.css" rel="stylesheet">

    <!-- Select 2 -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.12/css/select2.min.css">

</head>
<body id="page-top">
    <div class="Body-content">
        <!-- Page Wrapper -->
        <div id="wrapper">

            <?php include 'administration/Views/_Shared/sidebar.phtml'; ?>

            <!-- Content Wrapper -->
            <div id="content-wrapper" class="d-flex flex-column">
                <!-- Main Content -->
                <div id="content">

                    <?php include 'administration/Views/_Shared/topbar.phtml'; ?>

                    <!-- Begin Page Content -->
                    <div class="container-fluid">
                        <?= $bodyContent ?>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>
    
    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Vous avez fini ?</h5>
            <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">×</span>
            </button>
            </div>
            <div class="modal-body">Voulez-vous vraiment vous déconnecter ?</div>
            <div class="modal-footer">
            <button class="btn btn-secondary" type="button" data-dismiss="modal">Annuler</button>
            <a class="btn btn-primary" href="/admin/authentification">Déconnexion</a>
            </div>
        </div>
        </div>
    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="/administration/Content/vendor/jquery/jquery.min.js"></script>
    <script src="/administration/Content/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="/administration/Content/vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="/administration/Content/js/sb-admin-2.min.js"></script>

    <!-- Page level plugins -->
    <script src="/administration/Content/vendor/chart.js/Chart.min.js"></script>

    <!-- Page level custom scripts -->
    <script src="/administration/Content/js/demo/chart-area-demo.js"></script>
    <script src="/administration/Content/js/demo/chart-pie-demo.js"></script>

    <!-- Select 2 -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.12/js/select2.full.min.js"></script>
</body>
</html>