<!-- Sidebar -->
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="/admin/dashboard">
        <div class="sidebar-brand-icon rotate-n-15">
            <i class="fas fa-laugh-wink"></i>
        </div>
        <div class="sidebar-brand-text mx-3">MyMVC <sup>FINAL</sup></div>
    </a>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    <!-- Nav Item - Dashboard -->
    <li class="nav-item active">
    <a class="nav-link" href="/admin/dashboard">
        <i class="fas fa-fw fa-tachometer-alt"></i>
        <span>Dashboard</span></a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Heading -->
    <div class="sidebar-heading">
    Contenu
    </div>

    <!-- Nav Item - Pages Collapse Menu -->
    <li class="nav-item">
    <a class="nav-link" href="/admin/post">
    <i class="fa fa-space-shuttle" aria-hidden="true"></i>
        <span>Gestion des articles</span></a>
        <ul style="list-style-type: none;">
        <li class="nav-item">
            <a class="nav-link" href="/admin/post/add">
            <i class="fa fa-caret-right" aria-hidden="true"></i>
                <span>Ajout d'un article</span></a>
        </li>
        </ul>
    </li>

    <!-- Nav Item - Pages Collapse Menu -->
    <li class="nav-item">
    <a class="nav-link" href="/admin/category">
    <i class="fa fa-balance-scale" aria-hidden="true"></i>
        <span>Gestion des catégories</span></a>
        <ul style="list-style-type: none;">
        <li class="nav-item">
            <a class="nav-link" href="/admin/category/add">
                <i class="fa fa-plus-circle" aria-hidden="true"></i>
                <span>Ajout d'une catégorie</span></a>
        </li>
        </ul>
    </li>

    <li class="nav-item">
    <a class="nav-link" href="/admin/user">
        <i class="fa fa-user" aria-hidden="true"></i>
        <span>Gestion des utilisateurs</span></a>
        <ul style="list-style-type: none;">
        <li class="nav-item">
            <a class="nav-link" href="/admin/user/add">
            <i class="fa fa-user-plus" aria-hidden="true"></i>
                <span>Ajout d'un utilisateur</span></a>
        </li>
        </ul>
    </li>
    

    <!-- Nav Item - Pages Collapse Menu -->
    <!-- <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages" aria-expanded="true" aria-controls="collapsePages">
            <i class="fas fa-fw fa-folder"></i>
            <span>Pages</span>
        </a>
        <div id="collapsePages" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
            <h6 class="collapse-header">Login Screens:</h6>
            <a class="collapse-item" href="login.html">Login</a>
            <a class="collapse-item" href="register.html">Register</a>
            <a class="collapse-item" href="forgot-password.html">Forgot Password</a>
            <div class="collapse-divider"></div>
            <h6 class="collapse-header">Other Pages:</h6>
            <a class="collapse-item" href="404.html">404 Page</a>
            <a class="collapse-item" href="blank.html">Blank Page</a>
            </div>
        </div>
    </li> -->

    <!-- Divider -->
    <!-- <hr class="sidebar-divider d-none d-md-block"> -->

    <!-- Sidebar Toggler (Sidebar) -->
    <!-- <div class="text-center d-none d-md-inline">
    <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div> -->

</ul>
<!-- End of Sidebar -->
