<div class="d-flex justify-content-center">
  <div class="card border-primary mt-3 mb-3 center" style="max-width: 50rem;">
    <div class="card-header"><?= htmlentities($_SESSION['user']['username'])?></div>
    <div class="card-body">
      <h4 class="card-title"><?= htmlentities($_SESSION['user']['email'])?></h4>
      <p class="card-text">Prénom : <?= htmlentities($_SESSION['user']['firstname'])?></p>
      <p class="card-text">Nom : <?= htmlentities($_SESSION['user']['lastname'])?></p>
    </div>
  </div>
</div>
