<div class="row">
      <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
        <div class="card card-signin my-5">
          <div class="card-body">
            <h5 class="card-title text-center">Connexion</h5>
            <form class="form-signin" action="/user/login" method="post">
              <div class="form-label-group">
                <label>Email address</label>
                <input type="email" id="email" class="form-control" name="email" placeholder="Email address" required autofocus>
              </div>
              <div class="form-label-group">
                <label for="inputPassword">Password</label>
                <input type="password" id="userpwd" class="form-control" name="userpwd" placeholder="Password" required>
              </div>

              <button class="btn btn-lg btn-primary btn-block text-uppercase mt-4" type="submit">Connexion</button>
            </form>
            <a href="/user/register"><p class="text-center mt-3 mb-0">Tu es nouveau ? Inscris toi !</p></a>
          </div>
        </div>
      </div>
    </div>