<div class="row">

      
      <!-- /.col-lg-3 -->

      <div class="col-lg-3">

        <div class="card mt-4" style="max-width: 500px;">
          <img class="card-img-top img-fluid" src="<?= htmlentities($produit['imageUrl']) ?>" style="max-width: 500px; max-height: 500px;" alt="">
        </div>
      </div>
      <div class="col-lg-6 mt-4">
            <h3><?= htmlentities($produit['label']) ?></h3>
            <h4><?= htmlentities($produit['prix']) ?> €</h4>
            <p><?= htmlentities($produit['description']) ?></p>
            <!-- <span class="text-warning">&#9733; &#9733; &#9733; &#9733; &#9734;</span>
            4.0 stars <br> -->
            <form action="/panier" method="post" class=" mt-2">
            <div class="form-group">
              <label class="col-3 p-0">Quantité : 
                <input type="number" name="quantity" class="form-control" value="1">
              </label>
            </div>
            <div class="form-group">
              <input type="hidden"class="col-2" name="produit" value="<?= htmlentities($produit['id'])?>">
              <button type="submit" class="btn btn-primary card-link col-3">Ajouter au panier</button>
            </div>
              
              
            </form>
      </div>
        <!-- /.card -->

      </div>
      <!-- /.col-lg-9 -->

    </div>