<div class="row">
  

      <!-- <div class="col-lg-9">
        <div class="list-group">
          <a href="/category/" class="list-group-item bg-primary text-white">Voir toutes les catégories</a>
          <?php foreach($categories as $category): ?>
            <a href="/category/details/<?=$category['id']?>" class="list-group-item text-primary"><?= $category['name']?></a>
          <?php endforeach ?>
        </div>
      </div> -->
      <!-- /.col-lg-3 -->

      <div class="col-lg-12">

        <!-- <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
          <ol class="carousel-indicators">
            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
          </ol>
          <div class="carousel-inner" role="listbox">
            <div class="carousel-item active">
              <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="First slide">
            </div>
            <div class="carousel-item">
              <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="Second slide">
            </div>
            <div class="carousel-item">
              <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="Third slide">
            </div>
          </div>
          <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div> -->
        <!-- /.row -->

        <div class="row blog">
          <?php foreach($categories as $category): ?>
            <h2><?= $category['name'] ?></h2>
                <div class="col-md-12">
                    <div id="blogCarousel<?= $category['id']?>" class="carousel slide" data-ride="carousel">
                        <ol class="carousel-indicators">
                            <li data-target="#blogCarousel" data-slide-to="0" class="active"></li>
                            <li data-target="#blogCarousel" data-slide-to="1"></li>
                        </ol>

                        <!-- Carousel items -->
                        <div class="carousel-inner">
                            <div class="carousel-item active">
                                <div class="row">
                                    <?php for ($i=1; $i < 5; $i++) {  ?>
                                        <?php if(!empty($category[0][$i])): ?>
                                        <div class="col mb-3">
                                          <div class="card h-100">
                                          <a href="/produit/details/<?=$category[0][$i]['id']?>" style="overflow: hidden; height: 250px;"><img class="card-img-top" src="<?= htmlentities($category[0][$i]['imageUrl'])?>" style="height: 250px;" alt="<?= htmlentities($category[0][$i]['label'])?>"></a>
                                            <div class="card-body">
                                              <h4 class="card-title">
                                                <a class="text-primary" href="/produit/details/<?=$category[0][$i]['id']?>"><?= htmlentities($category[0][$i]['label'])?></a>
                                              </h4>
                                              <h5><?= htmlentities($category[0][$i]['prix']) ?> €</h5>
                                              <p class="card-text"><?= htmlentities($category[0][$i]['description']) ?></p>
                                            </div>
                                            <!-- <div class="card-footer">
                                              <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9734;</small>
                                            </div> -->
                                          </div>
                                        </div>
                                        <?php else: ?>
                                          <div class="col mb-3">
                                          <div class="card h-100 align-items-center justify-content-center" style="width: 18rem;">
                                          <div class="card-body ">
                                            <a href="#" class="card-link">Voir toutes la catégorie</a>
                                          </div>
                                        </div>
                                          </div>
                                      <?php endif ?>
                                  <?php } ?>
                                </div>
                                <!--.row-->
                            </div>
                            <!--.item-->

                            <div class="carousel-item">
                                <div class="row">
                                  <?php for ($i=5; $i < 9; $i++) {  ?>
                                      <?php if(!empty($category[0][$i])): ?>
                                      <div class="col mb-3">
                                        <div class="card h-100">
                                        <a href="/produit/details/<?=$category[0][$i]['id']?>" style="overflow: hidden; height: 250px;"><img class="card-img-top" src="<?= htmlentities($category[0][$i]['imageUrl'])?>" style="height: 250px;" alt="<?= htmlentities($category[0][$i]['label'])?>"></a>
                                          <div class="card-body">
                                            <h4 class="card-title">
                                              <a class="text-primary" href="/produit/details/<?=$category[0][$i]['id']?>"><?= htmlentities($category[0][$i]['label'])?></a>
                                            </h4>
                                            <h5><?= htmlentities($category[0][$i]['prix']) ?> €</h5>
                                            <p class="card-text"><?= htmlentities($category[0][$i]['description']) ?></p>
                                          </div>
                                          <!-- <div class="card-footer">
                                            <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9734;</small>
                                          </div> -->
                                        </div>
                                      </div>
                                      <?php else: ?>
                                        <div class="col mb-3">
                                        <div class="card h-100 align-items-center justify-content-center" style="width: 18rem;">
                                        <div class="card-body ">
                                          <a href="#" class="card-link">Voir toutes la catégorie</a>
                                        </div>
                                      </div>
                                        </div>
                                      <?php endif ?>
                                  <?php } ?>
                                </div>
                                <!--.row-->
                            </div>
                            <!--.item-->
                        </div>
                        <!--.carousel-inner-->
                    </div>
                    <a class="carousel-control-prev" href="#blogCarousel<?=$category['id']?>" style="height: 50px; width: 50px;" role="button" data-slide="prev">
                      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                      <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#blogCarousel<?=$category['id']?>" style="height: 50px; width: 50px;" role="button" data-slide="next">
                      <span class="carousel-control-next-icon" aria-hidden="true"></span>
                      <span class="sr-only">Next</span>
                    </a>
                    <!--.Carousel-->
                </div>
              <?php endforeach ?>
        </div>
    </div>
  </div>