<div class=" border rounded p-2">
    <h3>Modifier un article</h3>
    <form class="w-100" action="/admin/post/edit/<?= $product['id']?>" method="post">
    <div class="form-group">
        <label>Nom de l'article
            <input type="text" class="form-control" id="label" name="label" placeholder="Enter label" value="<?= htmlentities($product['label']) ?>">
        </label>
    </div>
    <div class="form-group">
        <label>Description
            <textarea class="form-control" id="description" name="description" placeholder="Enter description" row="3"><?= htmlentities($product['description']) ?></textarea>
        </label>
    </div>
    <div class="form-group">
        <label>Image Url
            <input type="text" class="form-control" id="imageUrl" name="imageUrl" placeholder="Enter http://imageurl" value="<?= htmlentities($product['imageUrl']) ?>">
        </label>
    </div>
    <div class="form-group">
        <label>Prix
            <input type="number" class="form-control" id="prix" name="prix" placeholder="Enter prix" value="<?= htmlentities($product['prix']) ?>">
        </label>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>