<div class=" border rounded p-2">
    <h3>Ajouter un article</h3>
    <form class="w-100" action="/admin/user/add" method="post">
    <div class="form-group">
        <label>Pseudo
        <input type="text" class="form-control" id="username" name="username" placeholder="Enter email">
        </label>
    </div>
    <div class="form-group">
        <label>Email
            <input type="text" class="form-control" id="email" name="email" placeholder="Enter email">
        </label>
    </div>
    <div class="form-group">
        <label>Prénom
            <input type="text" class="form-control" id="firstname" name="firstname" placeholder="Enter prenom">
        </label>
    </div>
    <div class="form-group">
        <label>Nom
            <input type="text" class="form-control" id="lastname" name="lastname" placeholder="Enter nom">
        </label>
    </div>
    <div class="form-group">
        <label>Role
            <input type="text" class="form-control" id="roleUser" name="roleUser" placeholder="Enter role">
        </label>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>